import '../models/models.dart';
import 'firebase_service.dart';

class MigrationService {
  final FirebaseService _firebaseService;

  MigrationService(this._firebaseService);

  /// Migrar todas las máquinas existentes a Firebase
  Future<void> migrateMachines() async {
    final isEmpty = await _firebaseService.isMachinesCollectionEmpty();
    if (!isEmpty) return; // Ya hay datos

    final machines = _getDefaultMachines();
    await _firebaseService.saveMachinesBatch(machines);
  }

  /// Migrar todas las rutinas existentes a Firebase
  Future<void> migrateRoutines() async {
    final isEmpty = await _firebaseService.isRoutinesCollectionEmpty();
    if (!isEmpty) return; // Ya hay datos

    final routines = _getDefaultRoutines();
    await _firebaseService.saveRoutinesBatch(routines);
  }

  /// Migrar todo y ejecutar tareas de limpieza
  Future<void> migrateAll() async {
    await migrateMachines();
    await migrateRoutines();

    // Ejecutar limpieza de datos antiguos
    await _firebaseService.runCleanupTasks();
  }

  /// Lista de máquinas predefinidas (35 máquinas)
  List<MachineModel> _getDefaultMachines() {
    return [
      // CARDIO (5)
      const MachineModel(
        id: 'treadmill',
        nombre: 'Caminadora',
        descripcion: 'Banda motorizada para caminar, trotar o correr en interiores. Ideal para cardio y calentamiento.',
        categoria: MachineCategory.cardio,
        tipo: MachineType.maquina,
        nivel: DifficultyLevel.principiante,
        defaultSets: 1,
        defaultReps: 20,
        imageUrl: 'https://images.unsplash.com/photo-1576678927484-cc907957088c?w=400',
        tips: [
          'Comienza con una velocidad baja para calentar',
          'Mantén una postura erguida',
          'Usa el agarre solo para equilibrio, no para soportar peso',
        ],
        erroresComunes: [
          'Correr con zancadas demasiado largas',
          'Mirar hacia abajo constantemente',
          'Agarrarse demasiado fuerte de los pasamanos',
        ],
      ),
      const MachineModel(
        id: 'stationary_bike',
        nombre: 'Bicicleta Estática',
        descripcion: 'Máquina de ciclismo para cardio de bajo impacto. Resistencia ajustable para variar la intensidad.',
        categoria: MachineCategory.cardio,
        tipo: MachineType.maquina,
        nivel: DifficultyLevel.principiante,
        defaultSets: 1,
        defaultReps: 15,
        imageUrl: 'https://images.unsplash.com/photo-1591741535018-d042cbcd0d73?w=400',
        tips: [
          'Ajusta el asiento a la altura de tu cadera',
          'Mantén los pies bien sujetos en los pedales',
          'Varía la resistencia durante el ejercicio',
        ],
        erroresComunes: [
          'Asiento muy alto o muy bajo',
          'Pedalear solo con las puntas de los pies',
          'Encorvarse sobre el manillar',
        ],
      ),
      const MachineModel(
        id: 'elliptical',
        nombre: 'Elíptica',
        descripcion: 'Máquina de cardio de bajo impacto que simula caminar, correr o subir escaleras.',
        categoria: MachineCategory.cardio,
        tipo: MachineType.maquina,
        nivel: DifficultyLevel.principiante,
        defaultSets: 1,
        defaultReps: 15,
        imageUrl: 'https://images.unsplash.com/photo-1570829460005-c840387bb1ca?w=400',
        tips: [
          'Mantén los pies planos en los pedales',
          'Usa los brazos activamente para un ejercicio de cuerpo completo',
          'Varía la inclinación para trabajar diferentes músculos',
        ],
        erroresComunes: [
          'Apoyarse demasiado en las barras fijas',
          'Movimiento excesivamente rápido sin control',
          'Postura encorvada',
        ],
      ),
      const MachineModel(
        id: 'rowing_machine',
        nombre: 'Máquina de Remo',
        descripcion: 'Entrenamiento cardio de cuerpo completo simulando remo. Trabaja piernas, core y tren superior.',
        categoria: MachineCategory.cardio,
        categoriaSecundaria: MachineCategory.espalda,
        tipo: MachineType.maquina,
        nivel: DifficultyLevel.intermedio,
        defaultSets: 3,
        defaultReps: 15,
        imageUrl: 'https://images.unsplash.com/photo-1519505907962-0a6cb0167c73?w=400',
        tips: [
          'La secuencia es: piernas, core, brazos',
          'Mantén la espalda recta durante todo el movimiento',
          'No tires solo con los brazos',
        ],
        erroresComunes: [
          'Tirar primero con los brazos antes que las piernas',
          'Redondear la espalda',
          'Movimiento descoordinado',
        ],
      ),
      const MachineModel(
        id: 'step_stepper',
        nombre: 'Escaladora',
        descripcion: 'Simula subir escaleras para cardio y tonificación del tren inferior.',
        categoria: MachineCategory.cardio,
        categoriaSecundaria: MachineCategory.pierna,
        tipo: MachineType.maquina,
        nivel: DifficultyLevel.intermedio,
        defaultSets: 1,
        defaultReps: 15,
        imageUrl: 'https://images.unsplash.com/photo-1534258936925-c58bed479fcb?w=400',
        tips: [
          'Mantén el cuerpo erguido',
          'Da pasos completos, no cortos',
          'Usa los pasamanos solo para equilibrio',
        ],
        erroresComunes: [
          'Inclinarse demasiado hacia adelante',
          'Agarrarse fuerte de los pasamanos',
          'Pasos muy cortos y rápidos',
        ],
      ),

      // LEGS (8)
      const MachineModel(
        id: 'leg_press',
        nombre: 'Prensa de Piernas',
        descripcion: 'Máquina sentada para empujar peso con las piernas. Trabaja cuádriceps, isquiotibiales y glúteos.',
        categoria: MachineCategory.pierna,
        tipo: MachineType.maquina,
        nivel: DifficultyLevel.principiante,
        defaultSets: 4,
        defaultReps: 12,
        imageUrl: 'https://images.unsplash.com/photo-1434682881908-b43d0467b798?w=400',
        tips: [
          'Coloca los pies a la anchura de los hombros',
          'No bloquees las rodillas al extender',
          'Baja controladamente hasta 90 grados',
        ],
        erroresComunes: [
          'Bloquear las rodillas completamente',
          'Levantar los glúteos del asiento',
          'Usar demasiado peso sin control',
        ],
      ),
      const MachineModel(
        id: 'smith_machine',
        nombre: 'Máquina Smith',
        descripcion: 'Barra fija en rieles de acero para sentadillas, press y remos guiados.',
        categoria: MachineCategory.pierna,
        tipo: MachineType.maquina,
        nivel: DifficultyLevel.intermedio,
        defaultSets: 4,
        defaultReps: 10,
        imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400',
        tips: [
          'Asegúrate de que los topes de seguridad estén bien posicionados',
          'Mantén los pies ligeramente adelantados para sentadillas',
          'Controla el movimiento en todo momento',
        ],
        erroresComunes: [
          'No usar los seguros',
          'Pies demasiado cerca de la barra',
          'Arquear excesivamente la espalda',
        ],
      ),
      const MachineModel(
        id: 'squat_rack',
        nombre: 'Rack de Sentadillas',
        descripcion: 'Estructura resistente para sentadillas con barra. Esencial para desarrollar fuerza en piernas.',
        categoria: MachineCategory.pierna,
        tipo: MachineType.pesoLibre,
        nivel: DifficultyLevel.intermedio,
        defaultSets: 4,
        defaultReps: 10,
        imageUrl: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400',
        tips: [
          'Coloca la barra a la altura del pecho',
          'Usa los seguros de seguridad',
          'Mantén el core activado durante todo el movimiento',
        ],
        erroresComunes: [
          'Rodillas hacia adentro al bajar',
          'Talones despegados del suelo',
          'No usar seguridades',
        ],
      ),
      const MachineModel(
        id: 'hack_squat',
        nombre: 'Hack Squat',
        descripcion: 'Máquina inclinada para sentadillas. Enfatiza cuádriceps con soporte de espalda.',
        categoria: MachineCategory.pierna,
        tipo: MachineType.maquina,
        nivel: DifficultyLevel.intermedio,
        defaultSets: 4,
        defaultReps: 12,
        imageUrl: 'https://images.unsplash.com/photo-1581009146145-b5ef050c149a?w=400',
        tips: [
          'Mantén la espalda completamente apoyada',
          'Pies a la anchura de los hombros',
          'Baja hasta que los muslos estén paralelos',
        ],
        erroresComunes: [
          'Despegar la espalda del respaldo',
          'Rodillas sobrepasando mucho los pies',
          'Movimiento parcial',
        ],
      ),
      const MachineModel(
        id: 'leg_extension',
        nombre: 'Extensión de Piernas',
        descripcion: 'Máquina sentada que aísla los cuádriceps mediante extensión de rodilla.',
        categoria: MachineCategory.pierna,
        tipo: MachineType.maquina,
        nivel: DifficultyLevel.principiante,
        defaultSets: 3,
        defaultReps: 15,
        imageUrl: 'https://images.unsplash.com/photo-1558611848-73f7eb4001a1?w=400',
        tips: [
          'Ajusta el rodillo justo encima del tobillo',
          'Extiende completamente sin bloquear',
          'Contrae el cuádriceps en la parte superior',
        ],
        erroresComunes: [
          'Usar impulso para levantar',
          'Rodillo mal posicionado',
          'Bajar demasiado rápido',
        ],
      ),
      const MachineModel(
        id: 'leg_curl',
        nombre: 'Curl de Piernas',
        descripcion: 'Máquina para aislar isquiotibiales mediante flexión de rodilla. Disponible sentado o acostado.',
        categoria: MachineCategory.pierna,
        tipo: MachineType.maquina,
        nivel: DifficultyLevel.principiante,
        defaultSets: 3,
        defaultReps: 15,
        imageUrl: 'https://images.unsplash.com/photo-1597452485669-2c7bb5fef90d?w=400',
        tips: [
          'Mantén las caderas pegadas al banco',
          'Flexiona completamente llevando el talón al glúteo',
          'Movimiento controlado en ambas direcciones',
        ],
        erroresComunes: [
          'Levantar las caderas del banco',
          'Usar impulso',
          'Rango de movimiento incompleto',
        ],
      ),
      const MachineModel(
        id: 'calf_raise',
        nombre: 'Máquina de Pantorrillas',
        descripcion: 'Trabaja los músculos de la pantorrilla mediante flexión plantar. Versiones de pie o sentado.',
        categoria: MachineCategory.pierna,
        tipo: MachineType.maquina,
        nivel: DifficultyLevel.principiante,
        defaultSets: 4,
        defaultReps: 15,
        imageUrl: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400',
        tips: [
          'Sube hasta la máxima contracción',
          'Baja estirando bien el músculo',
          'Pausa en la parte superior',
        ],
        erroresComunes: [
          'Rango de movimiento muy corto',
          'Rebotes en la parte inferior',
          'Usar demasiado peso',
        ],
      ),
      const MachineModel(
        id: 'abductor_adductor',
        nombre: 'Máquina Abductor/Aductor',
        descripcion: 'Trabaja la parte interna y externa de los muslos. Cambia configuración para abducción o aducción.',
        categoria: MachineCategory.pierna,
        tipo: MachineType.maquina,
        nivel: DifficultyLevel.principiante,
        defaultSets: 3,
        defaultReps: 15,
        imageUrl: 'https://images.unsplash.com/photo-1596357395217-80de13130e92?w=400',
        tips: [
          'Mantén la espalda apoyada en el respaldo',
          'Movimiento controlado y lento',
          'No uses impulso',
        ],
        erroresComunes: [
          'Movimientos bruscos',
          'Inclinarse hacia adelante',
          'Demasiado peso sacrificando el rango',
        ],
      ),

      // CHEST (5)
      const MachineModel(
        id: 'chest_press',
        nombre: 'Press de Pecho',
        descripcion: 'Máquina sentada para press horizontal. Aísla el pecho con movimiento guiado.',
        categoria: MachineCategory.pecho,
        tipo: MachineType.maquina,
        nivel: DifficultyLevel.principiante,
        defaultSets: 4,
        defaultReps: 12,
        imageUrl: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=400',
        tips: [
          'Ajusta el asiento para que las manijas estén a la altura del pecho',
          'Mantén los omóplatos retraídos',
          'No bloquees los codos al extender',
        ],
        erroresComunes: [
          'Arquear excesivamente la espalda',
          'Codos demasiado abiertos',
          'Asiento mal ajustado',
        ],
      ),
      const MachineModel(
        id: 'pec_deck',
        nombre: 'Pec Deck',
        descripcion: 'Aísla el pecho mediante aducción horizontal de brazos. Excelente para contracción del pecho.',
        categoria: MachineCategory.pecho,
        tipo: MachineType.maquina,
        nivel: DifficultyLevel.principiante,
        defaultSets: 3,
        defaultReps: 12,
        imageUrl: 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=400',
        tips: [
          'Mantén una ligera flexión en los codos',
          'Aprieta el pecho al juntar los brazos',
          'Controla el regreso',
        ],
        erroresComunes: [
          'Brazos completamente extendidos',
          'No juntar completamente las manijas',
          'Usar impulso del cuerpo',
        ],
      ),
      const MachineModel(
        id: 'cable_crossover',
        nombre: 'Cruce de Cables',
        descripcion: 'Estación de cables dobles para aperturas y cruces de pecho. Tensión constante.',
        categoria: MachineCategory.pecho,
        tipo: MachineType.funcional,
        nivel: DifficultyLevel.intermedio,
        defaultSets: 3,
        defaultReps: 12,
        imageUrl: 'https://images.unsplash.com/photo-1534368959876-26bf04f2c947?w=400',
        tips: [
          'Da un paso adelante para estabilidad',
          'Mantén una ligera inclinación hacia adelante',
          'Cruza las manos en el centro',
        ],
        erroresComunes: [
          'Usar demasiado peso',
          'Movimiento descontrolado',
          'No cruzar las manos lo suficiente',
        ],
      ),
      const MachineModel(
        id: 'dumbbell_bench_flat',
        nombre: 'Banco Plano con Mancuernas',
        descripcion: 'Banco plano para press y aperturas con mancuernas. Trabaja el pecho medio.',
        categoria: MachineCategory.pecho,
        tipo: MachineType.pesoLibre,
        nivel: DifficultyLevel.intermedio,
        defaultSets: 4,
        defaultReps: 10,
        imageUrl: 'https://images.unsplash.com/photo-1534368786749-b63e05c92717?w=400',
        tips: [
          'Pies firmes en el suelo',
          'Omóplatos retraídos y apretados',
          'Baja las mancuernas hasta el nivel del pecho',
        ],
        erroresComunes: [
          'Rebotar las mancuernas en el pecho',
          'Arquear demasiado la espalda',
          'Codos demasiado abiertos',
        ],
      ),
      const MachineModel(
        id: 'dumbbell_bench_incline',
        nombre: 'Banco Inclinado con Mancuernas',
        descripcion: 'Banco inclinado que enfatiza el desarrollo del pecho superior.',
        categoria: MachineCategory.pecho,
        tipo: MachineType.pesoLibre,
        nivel: DifficultyLevel.intermedio,
        defaultSets: 4,
        defaultReps: 10,
        imageUrl: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400',
        tips: [
          'Inclinación de 30-45 grados',
          'No dejes que los hombros dominen el movimiento',
          'Mantén el core activado',
        ],
        erroresComunes: [
          'Inclinación demasiado pronunciada',
          'Usar los hombros más que el pecho',
          'Movimiento asimétrico',
        ],
      ),

      // BACK (5)
      const MachineModel(
        id: 'lat_pulldown',
        nombre: 'Jalón al Pecho',
        descripcion: 'Máquina de cables para jalón vertical. Trabaja dorsales y espalda alta.',
        categoria: MachineCategory.espalda,
        tipo: MachineType.maquina,
        nivel: DifficultyLevel.principiante,
        defaultSets: 4,
        defaultReps: 12,
        imageUrl: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=400',
        tips: [
          'Agarre ligeramente más ancho que los hombros',
          'Tira hacia el pecho, no detrás de la cabeza',
          'Aprieta los omóplatos al bajar',
        ],
        erroresComunes: [
          'Tirar detrás de la cabeza',
          'Inclinarse demasiado hacia atrás',
          'Usar impulso del cuerpo',
        ],
      ),
      const MachineModel(
        id: 'seated_row',
        nombre: 'Remo Sentado',
        descripcion: 'Máquina de remo con cable para jalón horizontal. Trabaja espalda media y dorsales.',
        categoria: MachineCategory.espalda,
        tipo: MachineType.maquina,
        nivel: DifficultyLevel.principiante,
        defaultSets: 4,
        defaultReps: 12,
        imageUrl: 'https://images.unsplash.com/photo-1597347316205-36f6c451902a?w=400',
        tips: [
          'Mantén el pecho erguido',
          'Tira los codos hacia atrás',
          'Aprieta los omóplatos en la contracción',
        ],
        erroresComunes: [
          'Redondear la espalda',
          'Tirar solo con los brazos',
          'Balancear el torso',
        ],
      ),
      const MachineModel(
        id: 'assisted_pullup',
        nombre: 'Dominadas Asistidas',
        descripcion: 'Máquina con contrapeso para dominadas y chin-ups asistidos.',
        categoria: MachineCategory.espalda,
        tipo: MachineType.maquina,
        nivel: DifficultyLevel.principiante,
        defaultSets: 3,
        defaultReps: 10,
        imageUrl: 'https://images.unsplash.com/photo-1598266663439-2056e6900339?w=400',
        tips: [
          'Más peso en la máquina = más asistencia',
          'Sube hasta que la barbilla pase la barra',
          'Baja controladamente',
        ],
        erroresComunes: [
          'No completar el rango de movimiento',
          'Usar demasiada asistencia',
          'Balancearse',
        ],
      ),
      const MachineModel(
        id: 'iso_row',
        nombre: 'Remo con Soporte de Pecho',
        descripcion: 'Máquina de remo con soporte que aísla cada lado de forma independiente.',
        categoria: MachineCategory.espalda,
        tipo: MachineType.maquina,
        nivel: DifficultyLevel.principiante,
        defaultSets: 3,
        defaultReps: 12,
        imageUrl: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=400',
        tips: [
          'Pecho apoyado en el soporte',
          'Trabaja cada brazo por igual',
          'Contrae la espalda en cada repetición',
        ],
        erroresComunes: [
          'Despegar el pecho del soporte',
          'Tirar desigual con cada brazo',
          'Movimiento muy rápido',
        ],
      ),
      const MachineModel(
        id: 'barbell_rack',
        nombre: 'Rack de Barras',
        descripcion: 'Rack para barras usado en peso muerto, remos y otros ejercicios compuestos.',
        categoria: MachineCategory.espalda,
        tipo: MachineType.pesoLibre,
        nivel: DifficultyLevel.avanzado,
        defaultSets: 4,
        defaultReps: 8,
        imageUrl: 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=400',
        tips: [
          'Mantén la espalda neutra',
          'Activa el core antes de levantar',
          'Usa cinturón para pesos pesados',
        ],
        erroresComunes: [
          'Redondear la espalda',
          'No activar el core',
          'Levantar con la espalda en vez de las piernas',
        ],
      ),

      // SHOULDERS (2)
      const MachineModel(
        id: 'shoulder_press',
        nombre: 'Press de Hombros',
        descripcion: 'Máquina sentada para press sobre la cabeza. Trabaja deltoides de forma segura.',
        categoria: MachineCategory.hombro,
        tipo: MachineType.maquina,
        nivel: DifficultyLevel.principiante,
        defaultSets: 4,
        defaultReps: 12,
        imageUrl: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=400',
        tips: [
          'Espalda completamente apoyada',
          'No bloquees los codos arriba',
          'Baja hasta que los codos estén a 90 grados',
        ],
        erroresComunes: [
          'Arquear la espalda',
          'Usar impulso',
          'Bloquear los codos',
        ],
      ),
      const MachineModel(
        id: 'lateral_raise',
        nombre: 'Elevaciones Laterales',
        descripcion: 'Aísla los deltoides laterales mediante elevaciones con movimiento guiado.',
        categoria: MachineCategory.hombro,
        tipo: MachineType.maquina,
        nivel: DifficultyLevel.principiante,
        defaultSets: 3,
        defaultReps: 15,
        imageUrl: 'https://images.unsplash.com/photo-1532029837206-abbe2b7620e3?w=400',
        tips: [
          'Levanta hasta la altura de los hombros',
          'Ligera flexión en los codos',
          'Controla la bajada',
        ],
        erroresComunes: [
          'Subir más alto que los hombros',
          'Usar impulso del cuerpo',
          'Brazos completamente rectos',
        ],
      ),

      // ARMS (2)
      const MachineModel(
        id: 'triceps_pushdown',
        nombre: 'Jalón de Tríceps',
        descripcion: 'Máquina de cable o asistida para ejercicios de aislamiento de tríceps.',
        categoria: MachineCategory.brazo,
        tipo: MachineType.maquina,
        nivel: DifficultyLevel.principiante,
        defaultSets: 3,
        defaultReps: 12,
        imageUrl: 'https://images.unsplash.com/photo-1530822847156-5df684ec5ee1?w=400',
        tips: [
          'Codos pegados al cuerpo',
          'Extiende completamente los brazos',
          'Solo mueve los antebrazos',
        ],
        erroresComunes: [
          'Mover los codos',
          'Inclinarse sobre la polea',
          'Usar impulso',
        ],
      ),
      const MachineModel(
        id: 'biceps_curl',
        nombre: 'Curl de Bíceps',
        descripcion: 'Máquina sentada que aísla bíceps mediante flexión de codo.',
        categoria: MachineCategory.brazo,
        tipo: MachineType.maquina,
        nivel: DifficultyLevel.principiante,
        defaultSets: 3,
        defaultReps: 12,
        imageUrl: 'https://images.unsplash.com/photo-1581009137042-c552e485697a?w=400',
        tips: [
          'Brazos apoyados en el pad',
          'Sube hasta la máxima contracción',
          'Baja controladamente',
        ],
        erroresComunes: [
          'Levantar los codos del pad',
          'No extender completamente',
          'Usar impulso del cuerpo',
        ],
      ),

      // CORE (2)
      const MachineModel(
        id: 'ab_crunch',
        nombre: 'Máquina de Abdominales',
        descripcion: 'Máquina con peso para crunches abdominales con resistencia ajustable.',
        categoria: MachineCategory.core,
        tipo: MachineType.maquina,
        nivel: DifficultyLevel.principiante,
        defaultSets: 3,
        defaultReps: 20,
        imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400',
        tips: [
          'Flexiona el tronco, no tires con los brazos',
          'Exhala al contraer',
          'Movimiento controlado',
        ],
        erroresComunes: [
          'Tirar con los brazos',
          'Movimiento demasiado rápido',
          'No contraer los abdominales',
        ],
      ),
      const MachineModel(
        id: 'glute_machine',
        nombre: 'Máquina de Glúteos',
        descripcion: 'Trabaja glúteos mediante extensión de cadera. Ideal para desarrollar la cadena posterior.',
        categoria: MachineCategory.core,
        categoriaSecundaria: MachineCategory.pierna,
        tipo: MachineType.maquina,
        nivel: DifficultyLevel.principiante,
        defaultSets: 3,
        defaultReps: 15,
        imageUrl: 'https://images.unsplash.com/photo-1550345332-09e3ac987658?w=400',
        tips: [
          'Aprieta el glúteo en la extensión',
          'No arquees la espalda',
          'Movimiento controlado',
        ],
        erroresComunes: [
          'Arquear la espalda baja',
          'Usar impulso',
          'No apretar el glúteo',
        ],
      ),

      // FUNCTIONAL (6)
      const MachineModel(
        id: 'battle_ropes',
        nombre: 'Cuerdas de Batalla',
        descripcion: 'Cuerdas pesadas para acondicionamiento de alta intensidad. Trabaja todo el cuerpo.',
        categoria: MachineCategory.functional,
        tipo: MachineType.funcional,
        nivel: DifficultyLevel.intermedio,
        defaultSets: 3,
        defaultReps: 30,
        imageUrl: 'https://images.unsplash.com/photo-1517963879433-6ad2b056d712?w=400',
        tips: [
          'Mantén una postura atlética con rodillas flexionadas',
          'Genera el movimiento desde los hombros',
          'Mantén el core activado',
        ],
        erroresComunes: [
          'Estar de pie muy rígido',
          'Movimiento solo de brazos',
          'Perder la postura',
        ],
      ),
      const MachineModel(
        id: 'seated_chest_press',
        nombre: 'Press de Pecho Sentado',
        descripcion: 'Press de pecho alternativo con soporte vertical de espalda.',
        categoria: MachineCategory.pecho,
        tipo: MachineType.maquina,
        nivel: DifficultyLevel.principiante,
        defaultSets: 4,
        defaultReps: 12,
        imageUrl: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=400',
        tips: [
          'Ajusta el asiento correctamente',
          'Mantén la espalda apoyada',
          'No bloquees los codos',
        ],
        erroresComunes: [
          'Asiento mal ajustado',
          'Despegar la espalda',
          'Movimiento asimétrico',
        ],
      ),
      const MachineModel(
        id: 'multi_gym',
        nombre: 'Estación de Cables Multiusos',
        descripcion: 'Sistema de cables versátil para docenas de ejercicios. Entrenamiento de cuerpo completo.',
        categoria: MachineCategory.functional,
        tipo: MachineType.funcional,
        nivel: DifficultyLevel.intermedio,
        defaultSets: 3,
        defaultReps: 12,
        imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400',
        tips: [
          'Ajusta la altura según el ejercicio',
          'Mantén tensión constante',
          'Controla todo el movimiento',
        ],
        erroresComunes: [
          'Soltar el peso bruscamente',
          'Postura incorrecta',
          'Usar demasiado peso',
        ],
      ),
      const MachineModel(
        id: 'kettlebell_station',
        nombre: 'Estación de Kettlebells',
        descripcion: 'Rack con varios pesos de kettlebell para swings, cleans y press.',
        categoria: MachineCategory.functional,
        tipo: MachineType.pesoLibre,
        nivel: DifficultyLevel.intermedio,
        defaultSets: 3,
        defaultReps: 15,
        imageUrl: 'https://images.unsplash.com/photo-1517963879433-6ad2b056d712?w=400',
        tips: [
          'Domina la técnica con peso ligero primero',
          'El movimiento viene de la cadera',
          'Agarre firme en todo momento',
        ],
        erroresComunes: [
          'Levantar con la espalda',
          'Agarre flojo',
          'Rodillas hacia adentro',
        ],
      ),
      const MachineModel(
        id: 'trx_suspension',
        nombre: 'TRX Suspensión',
        descripcion: 'Sistema de entrenamiento con peso corporal usando correas de suspensión para fitness funcional.',
        categoria: MachineCategory.functional,
        tipo: MachineType.funcional,
        nivel: DifficultyLevel.intermedio,
        defaultSets: 3,
        defaultReps: 12,
        imageUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400',
        tips: [
          'Mantén tensión constante en las correas',
          'Core siempre activado',
          'Ajusta la dificultad con la posición del cuerpo',
        ],
        erroresComunes: [
          'Perder la tensión',
          'Core relajado',
          'Posición inicial incorrecta',
        ],
      ),
      const MachineModel(
        id: 'plyo_box',
        nombre: 'Caja Pliométrica',
        descripcion: 'Plataforma para saltos pliométricos y ejercicios de step. Desarrolla potencia explosiva.',
        categoria: MachineCategory.functional,
        categoriaSecundaria: MachineCategory.pierna,
        tipo: MachineType.funcional,
        nivel: DifficultyLevel.intermedio,
        defaultSets: 3,
        defaultReps: 10,
        imageUrl: 'https://images.unsplash.com/photo-1601422407692-ec4eeec1d9b3?w=400',
        tips: [
          'Aterriza suavemente con las rodillas flexionadas',
          'Usa los brazos para impulso',
          'Empieza con altura baja',
        ],
        erroresComunes: [
          'Aterrizar con piernas rígidas',
          'Caja demasiado alta para tu nivel',
          'No usar los brazos',
        ],
      ),
    ];
  }

  /// Lista de rutinas predefinidas con plantillas
  List<RoutineModel> _getDefaultRoutines() {
    return [
      // Plantillas rápidas
      RoutineModel(
        id: 'template_fullbody_45',
        nombre: 'Full Body 45 min',
        descripcion: 'Rutina completa de cuerpo en 45 minutos. Ideal para principiantes.',
        dificultad: RoutineDifficulty.principiante,
        parteDelCuerpo: RoutineBodyPart.fullBody,
        genero: RoutineGender.unisex,
        duracionMinutos: 45,
        esPlantilla: true,
        ejercicios: [
          const RoutineExercise(machineId: 'treadmill', machineName: 'Caminadora', sets: 1, reps: 10, orden: 0),
          const RoutineExercise(machineId: 'leg_press', machineName: 'Prensa de Piernas', sets: 3, reps: 12, orden: 1),
          const RoutineExercise(machineId: 'chest_press', machineName: 'Press de Pecho', sets: 3, reps: 12, orden: 2),
          const RoutineExercise(machineId: 'lat_pulldown', machineName: 'Jalón al Pecho', sets: 3, reps: 12, orden: 3),
          const RoutineExercise(machineId: 'shoulder_press', machineName: 'Press de Hombros', sets: 3, reps: 12, orden: 4),
          const RoutineExercise(machineId: 'ab_crunch', machineName: 'Máquina de Abdominales', sets: 3, reps: 15, orden: 5),
        ],
      ),
      RoutineModel(
        id: 'template_upper_hyper',
        nombre: 'Tren Superior Hipertrofia',
        descripcion: 'Enfocada en desarrollo muscular del tren superior.',
        dificultad: RoutineDifficulty.medio,
        parteDelCuerpo: RoutineBodyPart.trenSuperior,
        genero: RoutineGender.unisex,
        duracionMinutos: 60,
        esPlantilla: true,
        ejercicios: [
          const RoutineExercise(machineId: 'chest_press', machineName: 'Press de Pecho', sets: 4, reps: 10, orden: 0),
          const RoutineExercise(machineId: 'dumbbell_bench_incline', machineName: 'Banco Inclinado', sets: 4, reps: 10, orden: 1),
          const RoutineExercise(machineId: 'pec_deck', machineName: 'Pec Deck', sets: 3, reps: 12, orden: 2),
          const RoutineExercise(machineId: 'lat_pulldown', machineName: 'Jalón al Pecho', sets: 4, reps: 10, orden: 3),
          const RoutineExercise(machineId: 'seated_row', machineName: 'Remo Sentado', sets: 4, reps: 10, orden: 4),
          const RoutineExercise(machineId: 'shoulder_press', machineName: 'Press de Hombros', sets: 4, reps: 10, orden: 5),
          const RoutineExercise(machineId: 'lateral_raise', machineName: 'Elevaciones Laterales', sets: 3, reps: 15, orden: 6),
          const RoutineExercise(machineId: 'triceps_pushdown', machineName: 'Jalón de Tríceps', sets: 3, reps: 12, orden: 7),
          const RoutineExercise(machineId: 'biceps_curl', machineName: 'Curl de Bíceps', sets: 3, reps: 12, orden: 8),
        ],
      ),
      RoutineModel(
        id: 'template_glute_leg_a',
        nombre: 'Glúteo/Pierna Día A',
        descripcion: 'Enfoque en cuádriceps y glúteos.',
        dificultad: RoutineDifficulty.medio,
        parteDelCuerpo: RoutineBodyPart.pierna,
        genero: RoutineGender.mujer,
        duracionMinutos: 60,
        esPlantilla: true,
        ejercicios: [
          const RoutineExercise(machineId: 'treadmill', machineName: 'Caminadora', sets: 1, reps: 10, orden: 0),
          const RoutineExercise(machineId: 'squat_rack', machineName: 'Sentadillas', sets: 4, reps: 10, orden: 1),
          const RoutineExercise(machineId: 'leg_press', machineName: 'Prensa de Piernas', sets: 4, reps: 12, orden: 2),
          const RoutineExercise(machineId: 'leg_extension', machineName: 'Extensión de Piernas', sets: 3, reps: 15, orden: 3),
          const RoutineExercise(machineId: 'glute_machine', machineName: 'Máquina de Glúteos', sets: 4, reps: 12, orden: 4),
          const RoutineExercise(machineId: 'abductor_adductor', machineName: 'Abductor/Aductor', sets: 3, reps: 15, orden: 5),
          const RoutineExercise(machineId: 'calf_raise', machineName: 'Pantorrillas', sets: 4, reps: 15, orden: 6),
        ],
      ),
      RoutineModel(
        id: 'template_back_shoulder_b',
        nombre: 'Espalda/Hombro Día B',
        descripcion: 'Desarrollo de espalda y hombros.',
        dificultad: RoutineDifficulty.medio,
        parteDelCuerpo: RoutineBodyPart.espalda,
        genero: RoutineGender.unisex,
        duracionMinutos: 60,
        esPlantilla: true,
        ejercicios: [
          const RoutineExercise(machineId: 'lat_pulldown', machineName: 'Jalón al Pecho', sets: 4, reps: 10, orden: 0),
          const RoutineExercise(machineId: 'seated_row', machineName: 'Remo Sentado', sets: 4, reps: 10, orden: 1),
          const RoutineExercise(machineId: 'assisted_pullup', machineName: 'Dominadas Asistidas', sets: 3, reps: 10, orden: 2),
          const RoutineExercise(machineId: 'iso_row', machineName: 'Remo con Soporte', sets: 3, reps: 12, orden: 3),
          const RoutineExercise(machineId: 'shoulder_press', machineName: 'Press de Hombros', sets: 4, reps: 10, orden: 4),
          const RoutineExercise(machineId: 'lateral_raise', machineName: 'Elevaciones Laterales', sets: 4, reps: 15, orden: 5),
          const RoutineExercise(machineId: 'cable_crossover', machineName: 'Rear Delt en Cables', sets: 3, reps: 15, orden: 6),
        ],
      ),

      // Rutinas por nivel - Principiante
      RoutineModel(
        id: 'routine_full_body_beginner',
        nombre: 'Fuerza Cuerpo Completo',
        descripcion: 'Rutina de introducción para desarrollar fuerza general.',
        dificultad: RoutineDifficulty.principiante,
        parteDelCuerpo: RoutineBodyPart.fullBody,
        genero: RoutineGender.hombre,
        duracionMinutos: 60,
        ejercicios: [
          const RoutineExercise(machineId: 'treadmill', machineName: 'Caminadora', sets: 1, reps: 10, orden: 0),
          const RoutineExercise(machineId: 'leg_press', machineName: 'Prensa de Piernas', sets: 4, reps: 12, orden: 1),
          const RoutineExercise(machineId: 'chest_press', machineName: 'Press de Pecho', sets: 4, reps: 12, orden: 2),
          const RoutineExercise(machineId: 'lat_pulldown', machineName: 'Jalón al Pecho', sets: 4, reps: 12, orden: 3),
          const RoutineExercise(machineId: 'shoulder_press', machineName: 'Press de Hombros', sets: 3, reps: 12, orden: 4),
          const RoutineExercise(machineId: 'triceps_pushdown', machineName: 'Jalón de Tríceps', sets: 3, reps: 12, orden: 5),
          const RoutineExercise(machineId: 'biceps_curl', machineName: 'Curl de Bíceps', sets: 3, reps: 12, orden: 6),
          const RoutineExercise(machineId: 'ab_crunch', machineName: 'Abdominales', sets: 3, reps: 20, orden: 7),
        ],
      ),
      RoutineModel(
        id: 'routine_toning_beginner_w',
        nombre: 'Tonificación Cuerpo Completo',
        descripcion: 'Rutina de tonificación para mujeres principiantes.',
        dificultad: RoutineDifficulty.principiante,
        parteDelCuerpo: RoutineBodyPart.fullBody,
        genero: RoutineGender.mujer,
        duracionMinutos: 50,
        ejercicios: [
          const RoutineExercise(machineId: 'elliptical', machineName: 'Elíptica', sets: 1, reps: 10, orden: 0),
          const RoutineExercise(machineId: 'leg_press', machineName: 'Prensa de Piernas', sets: 3, reps: 15, orden: 1),
          const RoutineExercise(machineId: 'glute_machine', machineName: 'Máquina de Glúteos', sets: 3, reps: 15, orden: 2),
          const RoutineExercise(machineId: 'abductor_adductor', machineName: 'Abductor/Aductor', sets: 3, reps: 15, orden: 3),
          const RoutineExercise(machineId: 'chest_press', machineName: 'Press de Pecho', sets: 3, reps: 12, orden: 4),
          const RoutineExercise(machineId: 'lat_pulldown', machineName: 'Jalón al Pecho', sets: 3, reps: 12, orden: 5),
          const RoutineExercise(machineId: 'shoulder_press', machineName: 'Press de Hombros', sets: 3, reps: 12, orden: 6),
          const RoutineExercise(machineId: 'ab_crunch', machineName: 'Abdominales', sets: 3, reps: 20, orden: 7),
        ],
      ),

      // Rutinas por nivel - Medio
      RoutineModel(
        id: 'routine_upper_power_m',
        nombre: 'Potencia Tren Superior',
        descripcion: 'Rutina de fuerza para tren superior.',
        dificultad: RoutineDifficulty.medio,
        parteDelCuerpo: RoutineBodyPart.trenSuperior,
        genero: RoutineGender.hombre,
        duracionMinutos: 55,
        ejercicios: [
          const RoutineExercise(machineId: 'chest_press', machineName: 'Press de Pecho', sets: 4, reps: 10, orden: 0),
          const RoutineExercise(machineId: 'dumbbell_bench_flat', machineName: 'Banco Plano', sets: 4, reps: 10, orden: 1),
          const RoutineExercise(machineId: 'cable_crossover', machineName: 'Cruce de Cables', sets: 3, reps: 12, orden: 2),
          const RoutineExercise(machineId: 'lat_pulldown', machineName: 'Jalón al Pecho', sets: 4, reps: 10, orden: 3),
          const RoutineExercise(machineId: 'seated_row', machineName: 'Remo Sentado', sets: 4, reps: 10, orden: 4),
          const RoutineExercise(machineId: 'shoulder_press', machineName: 'Press de Hombros', sets: 4, reps: 10, orden: 5),
          const RoutineExercise(machineId: 'triceps_pushdown', machineName: 'Jalón de Tríceps', sets: 3, reps: 12, orden: 6),
          const RoutineExercise(machineId: 'biceps_curl', machineName: 'Curl de Bíceps', sets: 3, reps: 12, orden: 7),
        ],
      ),
      RoutineModel(
        id: 'routine_sculpt_upper_w',
        nombre: 'Esculpir Tren Superior',
        descripcion: 'Tonificación de brazos, espalda y hombros para mujeres.',
        dificultad: RoutineDifficulty.medio,
        parteDelCuerpo: RoutineBodyPart.trenSuperior,
        genero: RoutineGender.mujer,
        duracionMinutos: 45,
        ejercicios: [
          const RoutineExercise(machineId: 'chest_press', machineName: 'Press de Pecho', sets: 3, reps: 12, orden: 0),
          const RoutineExercise(machineId: 'pec_deck', machineName: 'Pec Deck', sets: 3, reps: 12, orden: 1),
          const RoutineExercise(machineId: 'lat_pulldown', machineName: 'Jalón al Pecho', sets: 3, reps: 12, orden: 2),
          const RoutineExercise(machineId: 'seated_row', machineName: 'Remo Sentado', sets: 3, reps: 12, orden: 3),
          const RoutineExercise(machineId: 'shoulder_press', machineName: 'Press de Hombros', sets: 3, reps: 12, orden: 4),
          const RoutineExercise(machineId: 'lateral_raise', machineName: 'Elevaciones Laterales', sets: 3, reps: 15, orden: 5),
          const RoutineExercise(machineId: 'triceps_pushdown', machineName: 'Jalón de Tríceps', sets: 3, reps: 15, orden: 6),
          const RoutineExercise(machineId: 'biceps_curl', machineName: 'Curl de Bíceps', sets: 3, reps: 15, orden: 7),
        ],
      ),

      // Rutinas de pierna
      RoutineModel(
        id: 'routine_leg_focus_m',
        nombre: 'Enfoque de Pierna',
        descripcion: 'Rutina intensiva de pierna para hombres.',
        dificultad: RoutineDifficulty.medio,
        parteDelCuerpo: RoutineBodyPart.pierna,
        genero: RoutineGender.hombre,
        duracionMinutos: 50,
        ejercicios: [
          const RoutineExercise(machineId: 'squat_rack', machineName: 'Sentadillas', sets: 4, reps: 10, orden: 0),
          const RoutineExercise(machineId: 'leg_press', machineName: 'Prensa de Piernas', sets: 4, reps: 12, orden: 1),
          const RoutineExercise(machineId: 'hack_squat', machineName: 'Hack Squat', sets: 4, reps: 10, orden: 2),
          const RoutineExercise(machineId: 'leg_extension', machineName: 'Extensión de Piernas', sets: 3, reps: 15, orden: 3),
          const RoutineExercise(machineId: 'leg_curl', machineName: 'Curl de Piernas', sets: 3, reps: 15, orden: 4),
          const RoutineExercise(machineId: 'calf_raise', machineName: 'Pantorrillas', sets: 4, reps: 15, orden: 5),
          const RoutineExercise(machineId: 'ab_crunch', machineName: 'Abdominales', sets: 3, reps: 20, orden: 6),
        ],
      ),
      RoutineModel(
        id: 'routine_leg_toning_w',
        nombre: 'Tonificación de Pierna',
        descripcion: 'Rutina de tonificación de pierna y glúteos para mujeres.',
        dificultad: RoutineDifficulty.medio,
        parteDelCuerpo: RoutineBodyPart.pierna,
        genero: RoutineGender.mujer,
        duracionMinutos: 45,
        ejercicios: [
          const RoutineExercise(machineId: 'elliptical', machineName: 'Elíptica', sets: 1, reps: 10, orden: 0),
          const RoutineExercise(machineId: 'leg_press', machineName: 'Prensa de Piernas', sets: 4, reps: 12, orden: 1),
          const RoutineExercise(machineId: 'glute_machine', machineName: 'Máquina de Glúteos', sets: 4, reps: 15, orden: 2),
          const RoutineExercise(machineId: 'leg_extension', machineName: 'Extensión de Piernas', sets: 3, reps: 15, orden: 3),
          const RoutineExercise(machineId: 'leg_curl', machineName: 'Curl de Piernas', sets: 3, reps: 15, orden: 4),
          const RoutineExercise(machineId: 'abductor_adductor', machineName: 'Abductor/Aductor', sets: 3, reps: 15, orden: 5),
          const RoutineExercise(machineId: 'calf_raise', machineName: 'Pantorrillas', sets: 3, reps: 15, orden: 6),
        ],
      ),

      // Rutinas avanzadas
      RoutineModel(
        id: 'routine_push_day',
        nombre: 'Push Day',
        descripcion: 'Día de empuje: pecho, hombros y tríceps.',
        dificultad: RoutineDifficulty.avanzado,
        parteDelCuerpo: RoutineBodyPart.trenSuperior,
        genero: RoutineGender.unisex,
        duracionMinutos: 50,
        ejercicios: [
          const RoutineExercise(machineId: 'dumbbell_bench_flat', machineName: 'Banco Plano', sets: 4, reps: 8, orden: 0),
          const RoutineExercise(machineId: 'dumbbell_bench_incline', machineName: 'Banco Inclinado', sets: 4, reps: 10, orden: 1),
          const RoutineExercise(machineId: 'cable_crossover', machineName: 'Cruce de Cables', sets: 3, reps: 12, orden: 2),
          const RoutineExercise(machineId: 'shoulder_press', machineName: 'Press de Hombros', sets: 4, reps: 10, orden: 3),
          const RoutineExercise(machineId: 'lateral_raise', machineName: 'Elevaciones Laterales', sets: 4, reps: 12, orden: 4),
          const RoutineExercise(machineId: 'triceps_pushdown', machineName: 'Jalón de Tríceps', sets: 4, reps: 12, orden: 5),
          const RoutineExercise(machineId: 'pec_deck', machineName: 'Pec Deck', sets: 3, reps: 12, orden: 6),
          const RoutineExercise(machineId: 'ab_crunch', machineName: 'Abdominales', sets: 3, reps: 20, orden: 7),
        ],
      ),
      RoutineModel(
        id: 'routine_pull_day',
        nombre: 'Pull Day',
        descripcion: 'Día de jalón: espalda y bíceps.',
        dificultad: RoutineDifficulty.avanzado,
        parteDelCuerpo: RoutineBodyPart.trenSuperior,
        genero: RoutineGender.unisex,
        duracionMinutos: 55,
        ejercicios: [
          const RoutineExercise(machineId: 'barbell_rack', machineName: 'Peso Muerto', sets: 4, reps: 6, orden: 0),
          const RoutineExercise(machineId: 'lat_pulldown', machineName: 'Jalón al Pecho', sets: 4, reps: 10, orden: 1),
          const RoutineExercise(machineId: 'seated_row', machineName: 'Remo Sentado', sets: 4, reps: 10, orden: 2),
          const RoutineExercise(machineId: 'assisted_pullup', machineName: 'Dominadas', sets: 3, reps: 10, orden: 3),
          const RoutineExercise(machineId: 'iso_row', machineName: 'Remo con Soporte', sets: 3, reps: 12, orden: 4),
          const RoutineExercise(machineId: 'biceps_curl', machineName: 'Curl de Bíceps', sets: 4, reps: 10, orden: 5),
          const RoutineExercise(machineId: 'cable_crossover', machineName: 'Curl en Cable', sets: 3, reps: 12, orden: 6),
          const RoutineExercise(machineId: 'ab_crunch', machineName: 'Abdominales', sets: 3, reps: 20, orden: 7),
        ],
      ),

      // HIIT
      RoutineModel(
        id: 'routine_cardio_hiit',
        nombre: 'Cardio HIIT',
        descripcion: 'Entrenamiento de alta intensidad con intervalos.',
        dificultad: RoutineDifficulty.avanzado,
        parteDelCuerpo: RoutineBodyPart.fullBody,
        genero: RoutineGender.unisex,
        duracionMinutos: 30,
        ejercicios: [
          const RoutineExercise(machineId: 'treadmill', machineName: 'Caminadora Sprint', sets: 5, reps: 1, notas: '30 seg sprint, 30 seg descanso', orden: 0),
          const RoutineExercise(machineId: 'battle_ropes', machineName: 'Cuerdas de Batalla', sets: 4, reps: 30, orden: 1),
          const RoutineExercise(machineId: 'plyo_box', machineName: 'Box Jumps', sets: 4, reps: 10, orden: 2),
          const RoutineExercise(machineId: 'rowing_machine', machineName: 'Remo', sets: 4, reps: 1, notas: '250m sprints', orden: 3),
          const RoutineExercise(machineId: 'kettlebell_station', machineName: 'Kettlebell Swings', sets: 4, reps: 15, orden: 4),
          const RoutineExercise(machineId: 'step_stepper', machineName: 'Escaladora', sets: 3, reps: 1, notas: '2 min intenso', orden: 5),
        ],
      ),

      // Rutina Experto
      RoutineModel(
        id: 'routine_expert_strength',
        nombre: 'Fuerza Máxima',
        descripcion: 'Rutina de fuerza avanzada con ejercicios compuestos.',
        dificultad: RoutineDifficulty.experto,
        parteDelCuerpo: RoutineBodyPart.fullBody,
        genero: RoutineGender.hombre,
        duracionMinutos: 75,
        ejercicios: [
          const RoutineExercise(machineId: 'squat_rack', machineName: 'Sentadillas', sets: 5, reps: 5, orden: 0),
          const RoutineExercise(machineId: 'barbell_rack', machineName: 'Peso Muerto', sets: 5, reps: 5, orden: 1),
          const RoutineExercise(machineId: 'dumbbell_bench_flat', machineName: 'Press Banca', sets: 5, reps: 5, orden: 2),
          const RoutineExercise(machineId: 'assisted_pullup', machineName: 'Dominadas', sets: 4, reps: 8, orden: 3),
          const RoutineExercise(machineId: 'shoulder_press', machineName: 'Press Militar', sets: 4, reps: 6, orden: 4),
          const RoutineExercise(machineId: 'seated_row', machineName: 'Remo con Barra', sets: 4, reps: 8, orden: 5),
          const RoutineExercise(machineId: 'leg_press', machineName: 'Prensa de Piernas', sets: 4, reps: 10, orden: 6),
          const RoutineExercise(machineId: 'ab_crunch', machineName: 'Core', sets: 3, reps: 20, orden: 7),
        ],
      ),
    ];
  }
}
