// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0yU1pR14CELHcCY032UszE-qCJwQQmOI',
    appId: '1:589672531910:web:8aa4d474b4abf7751a94c7',
    messagingSenderId: '589672531910',
    projectId: 'mexican-bulking',
    authDomain: 'mexican-bulking.firebaseapp.com',
    storageBucket: 'mexican-bulking.firebasestorage.app',
    measurementId: 'G-MX3MK6Y9YJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcZfqmyuyEZ_PITe8azqTkX3wmgLQAgeM',
    appId: '1:589672531910:android:9c6e8717669d74ef1a94c7',
    messagingSenderId: '589672531910',
    projectId: 'mexican-bulking',
    storageBucket: 'mexican-bulking.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0E7eyObfO6DY7UAUVzbnJ2GpVMijWtww',
    appId: '1:589672531910:ios:04839abcb394b8e21a94c7',
    messagingSenderId: '589672531910',
    projectId: 'mexican-bulking',
    storageBucket: 'mexican-bulking.firebasestorage.app',
    iosClientId: '589672531910-a9gdede0e54p9mhti1m2a5ec54f96qvi.apps.googleusercontent.com',
    iosBundleId: 'com.example.gym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0E7eyObfO6DY7UAUVzbnJ2GpVMijWtww',
    appId: '1:589672531910:ios:04839abcb394b8e21a94c7',
    messagingSenderId: '589672531910',
    projectId: 'mexican-bulking',
    storageBucket: 'mexican-bulking.firebasestorage.app',
    iosClientId: '589672531910-a9gdede0e54p9mhti1m2a5ec54f96qvi.apps.googleusercontent.com',
    iosBundleId: 'com.example.gym',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0yU1pR14CELHcCY032UszE-qCJwQQmOI',
    appId: '1:589672531910:web:9830cf4f8069b58c1a94c7',
    messagingSenderId: '589672531910',
    projectId: 'mexican-bulking',
    authDomain: 'mexican-bulking.firebaseapp.com',
    storageBucket: 'mexican-bulking.firebasestorage.app',
    measurementId: 'G-WL5TS8JGB4',
  );
}
